use_frameworks!

target 'Retrofire_Example' do
  pod 'Retrofire', :path => '../'

  target 'Retrofire_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
